# Generated by Django 5.0.6 on 2024-06-04 18:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_rating_alter_album_release_date'),
        ('musician', '0002_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='musician.musician'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 0, 34, 39, 100488)),
        ),
    ]
